### ISSUE TITLE
FPS drop on block selection

### ISSUE THREAD

**Issue by rckymtnrfc** [ssblur/ParcelsAndPackages#2]
I seem to be having an issue with this mod in conjunction with Mantle (1.8.8-0.6).

If I have both Parcels and Packages (1.8.9_0.1.0a) and Mantle installed, when I look at a block and the selection wireframe displays, my FPS drops from 60 to approx 30-40. Looking away and the FPS jumps back up.  If I remove either mod, the problem disappears.  Adding in TInker's Construct doesn't seem to change anything.

With only these 3 mods, it's not really an issue as I'm still maintaining 30 FPS but when I add in the rest of my mods, I get around 30-40 FPS.  When adding in P&P it can drop to 10-20 FPS with a block selected.

I'm posting this as your issue since I've got about 60 other mods that don't seem to have this problem with Mantle.  It occurs after I add in P&P.

FYI, using Forge 1707.

Please let me know if you need anything else.

**Comment by ssblur** [comment]
Thank you for reporting this, I may ask that you update your forge version, though I am terribly sorry that my mod was involved in this.

That being said, I have found the source of the issue, and the next version of the mod will allow for the disabling of that feature.

**Comment by rckymtnrfc** [comment]
You mention being able to disable that feature.  What feature is causing that?

**Comment by ssblur** [comment]
It is a feature which allows you to view the contents of some blocks from my mod's inventories.

**Comment by ssblur** [comment]
Intended to close, thank you for bringing this information to my attention.

**Comment by BBoldt** [comment]
wtf man, this isn't a feature!

This issue is a MASSIVE FPS drop when looking at ANY block! It doesn't require any other mods, it's your mod alone.

You should probably reopen this issue.

**Comment by TehNut** [comment]
Agreed with @BBoldt. I drop from 150FPS to ~25. This really isn't acceptable... Even with a config. Something you're doing is *seriously* broken.

**Comment by rckymtnrfc** [comment]
Perhaps you should look into using WAILA to display on screen inventory information.  Who doesn't use WAILA?

**Comment by ssblur** [comment]
As I said, some of the code I used apparently disagrees with mantle. I have addressed the issue, a fix will be present in the next version. Further comments on this issue will not be responded to unless they contribute new information.

**Comment by ssblur** [comment]
I have tested the new version with around 20 different mods, the issues seem to have gone away, as my FPS, even on a laptop, remains fairly consistent. I will publish the new version after completing the changes which are currently in-progress.

Thank you for bearing with me through this process.

**Comment by rckymtnrfc** [comment]
Thanks for keeping us informed.  Looking forward to checking out your mod when the update is released.  =)

**Comment by ssblur** [comment]
Essentially, this issue was twofold: a) I forgot to remove a debugging feature which ended up being expensive memory-wise around other mods, and b) A mathematical error causing this overlay to be rendered a lot. Like, a lot a lot.

Terribly sorry about these issues, I plan to have the update posted in the next couple of hours, I just have to ensure this version will not encounter any such issues, and I wish to include one additional feature before updating.

Again, thank you for your patience, and for helping me improve my mod!
